openapi: 3.0.0
info:
  title: LibraNexus Catalog Service
  version: 1.0.0
paths:
  /items:
    post:
      summary: Add a new item to the catalog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemRequest'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      summary: Get an item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: An item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    patch:
      summary: Update item copies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCopiesRequest'
      responses:
        '200':
          description: Item updated
    delete:
      summary: Remove an item from the catalog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Item removed
  /search:
    get:
      summary: Search for items in the catalog
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        isbn:
          type: string
        title:
          type: string
        author:
          type: string
        total_copies:
          type: integer
        available:
          type: integer
        status:
          type: string
    AddItemRequest:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        author:
          type: string
        total_copies:
          type: integer
    UpdateCopiesRequest:
      type: object
      properties:
        total_copies:
          type: integer
        available:
          type: integer
