openapi: 3.0.0
info:
  title: LibraNexus Membership Service
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a new member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Member created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
  /login:
    post:
      summary: Authenticate a member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Member authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
  /members/{id}:
    get:
      summary: Get a member by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
components:
  schemas:
    Member:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
        membership_tier:
          type: string
        status:
          type: string
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
